apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-catalog-service
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-catalog-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-catalog-service
    spec:
      containers:
      - name: catalog-service
        image: {{ .Values.catalogService.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Release.Name }}-postgres:5432/catalog"
        ports:
        - containerPort: {{ .Values.catalogService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-catalog-service
spec:
  selector:
    app: {{ .Release.Name }}-catalog-service
  ports:
  - port: {{ .Values.catalogService.port }}
    targetPort: {{ .Values.catalogService.port }}
