{{- range $name, $svc := .Values.microservices }}
{{- if $svc.ingress.enabled }}
---
# Ingress for {{ $name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  {{- with $svc.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $svc.ingress.className }}
  rules:
    {{- range $svc.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $name }}
                port:
                  number: {{ $svc.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
