apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
      - name: ui
        image: {{ .Values.ui.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: CATALOG_SERVICE_URL
          value: "http://{{ .Release.Name }}-catalog-service:{{ .Values.catalogService.port }}"
        - name: ORDERS_SERVICE_URL
          value: "http://{{ .Release.Name }}-orders-service:{{ .Values.ordersService.port }}"
        ports:
        - containerPort: {{ .Values.ui.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  type: {{ .Values.ui.type }}
  selector:
    app: {{ .Release.Name }}-ui
  ports:
  - port: {{ .Values.ui.port }}
    targetPort: {{ .Values.ui.port }}
    nodePort: {{ .Values.ui.nodePort }}
