# Global configurations
postgres:
  image: "postgres:16-alpine"
  user: "microservices"
  password: "password"
  databases: "catalog,orders"
  port: 5432
  storage: "1Gi"

# Define all stateless microservices here
microservices:
  catalog-service:
    image:
      repository: catalog-service
      tag: latest
      pullPolicy: IfNotPresent
    service:
      port: 8000
      type: ClusterIP
    envSecret:
      DATABASE_URL: catalog-db-url
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    ingress:
      enabled: false

  orders-service:
    image:
      repository: orders-service
      tag: latest
      pullPolicy: IfNotPresent
    service:
      port: 8000
      type: ClusterIP
    envSecret:
      DATABASE_URL: orders-db-url
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    ingress:
      enabled: false

  ui:
    image:
      repository: ui
      tag: latest
      pullPolicy: IfNotPresent
    service:
      port: 8000
      type: NodePort
      nodePort: 30080
    env:
      CATALOG_SERVICE_URL: "http://{{ .Release.Name }}-catalog-service:8000"
      ORDERS_SERVICE_URL: "http://{{ .Release.Name }}-orders-service:8000"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
        - host: simpleproject.local
          paths:
            - path: /
              pathType: ImplementationSpecific
