apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: orders-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://microservices:password@postgres:5432/orders"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
  - port: 8000
    targetPort: 8000
